-- MySQL Script generated by MySQL Workbench
-- Wed 24 Mar 2021 08:50:55 AM -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema marlacedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `marlacedb` ;

-- -----------------------------------------------------
-- Schema marlacedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marlacedb` ;
USE `marlacedb` ;

-- -----------------------------------------------------
-- Table `marlacedb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marlacedb`.`users` ;

CREATE TABLE IF NOT EXISTS `marlacedb`.`users` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` TEXT NOT NULL,
  `description` VARCHAR(1024) NULL,
  `profile_image_url` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `marlacedb`.`projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marlacedb`.`projects` ;

CREATE TABLE IF NOT EXISTS `marlacedb`.`projects` (
  `project_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(128) NOT NULL,
  `description` VARCHAR(1024) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`project_id`),
  UNIQUE INDEX `project_id_UNIQUE` (`project_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `marlacedb`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marlacedb`.`tags` ;

CREATE TABLE IF NOT EXISTS `marlacedb`.`tags` (
  `tag_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`tag_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `marlacedb`.`issues`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marlacedb`.`issues` ;

CREATE TABLE IF NOT EXISTS `marlacedb`.`issues` (
  `issue_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` INT UNSIGNED NOT NULL,
  `tag_id` INT UNSIGNED NULL,
  `created_by` INT UNSIGNED NOT NULL,
  `title` VARCHAR(128) NOT NULL,
  `body` LONGTEXT NOT NULL,
  `resolved` TINYINT NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`issue_id`, `project_id`, `created_by`),
  UNIQUE INDEX `issue_id_UNIQUE` (`issue_id` ASC) VISIBLE,
  INDEX `fk_issues_projects1_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_issues_users1_idx` (`created_by` ASC) VISIBLE,
  INDEX `fk_issues_tags1_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_issues_projects1`
    FOREIGN KEY (`project_id`)
    REFERENCES `marlacedb`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `marlacedb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_issues_tags1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `marlacedb`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `marlacedb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marlacedb`.`roles` ;

CREATE TABLE IF NOT EXISTS `marlacedb`.`roles` (
  `role_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(64) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`role_id`),
  UNIQUE INDEX `role_id_UNIQUE` (`role_id` ASC) VISIBLE,
  UNIQUE INDEX `title_UNIQUE` (`title` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `marlacedb`.`users_has_projects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marlacedb`.`users_has_projects` ;

CREATE TABLE IF NOT EXISTS `marlacedb`.`users_has_projects` (
  `user_id` INT UNSIGNED NOT NULL,
  `project_id` INT UNSIGNED NOT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `project_id`, `role_id`),
  INDEX `fk_projects_has_users_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_projects_has_users_projects_idx` (`project_id` ASC) VISIBLE,
  INDEX `fk_users_has_projects_roles1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_has_users_projects`
    FOREIGN KEY (`project_id`)
    REFERENCES `marlacedb`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_users_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `marlacedb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_projects_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `marlacedb`.`roles` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `marlacedb`.`projects_has_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marlacedb`.`projects_has_tags` ;

CREATE TABLE IF NOT EXISTS `marlacedb`.`projects_has_tags` (
  `projects_project_id` INT UNSIGNED NOT NULL,
  `tags_tag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`projects_project_id`, `tags_tag_id`),
  INDEX `fk_projects_has_tags_tags1_idx` (`tags_tag_id` ASC) VISIBLE,
  INDEX `fk_projects_has_tags_projects1_idx` (`projects_project_id` ASC) VISIBLE,
  CONSTRAINT `fk_projects_has_tags_projects1`
    FOREIGN KEY (`projects_project_id`)
    REFERENCES `marlacedb`.`projects` (`project_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projects_has_tags_tags1`
    FOREIGN KEY (`tags_tag_id`)
    REFERENCES `marlacedb`.`tags` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `marlacedb`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marlacedb`.`comments` ;

CREATE TABLE IF NOT EXISTS `marlacedb`.`comments` (
  `comment_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `issue_id` INT UNSIGNED NOT NULL,
  `created_by` INT UNSIGNED NOT NULL,
  `comment` TEXT NOT NULL,
  `replied_to` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'If the value is zero (the default value) it means that the comment is a \"parent comment\" (i.e., it is not a reply).',
  `has_replies` TINYINT NOT NULL DEFAULT 0,
  `likes` INT UNSIGNED NOT NULL DEFAULT 0,
  `dislikes` INT UNSIGNED NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`comment_id`, `issue_id`, `created_by`),
  INDEX `fk_comments_issues1_idx` (`issue_id` ASC) VISIBLE,
  INDEX `fk_comments_users1_idx` (`created_by` ASC) VISIBLE,
  UNIQUE INDEX `comment_id_UNIQUE` (`comment_id` ASC) VISIBLE,
  INDEX `fk_comments_comments1_idx` (`replied_to` ASC) VISIBLE,
  CONSTRAINT `fk_comments_issues1`
    FOREIGN KEY (`issue_id`)
    REFERENCES `marlacedb`.`issues` (`issue_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`created_by`)
    REFERENCES `marlacedb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comments_comments1`
    FOREIGN KEY (`replied_to`)
    REFERENCES `marlacedb`.`comments` (`comment_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
