-- MySQL Script generated by MySQL Workbench
-- Tue 09 Mar 2021 11:17:52 PM -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema marlacedb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `marlacedb` ;

-- -----------------------------------------------------
-- Schema marlacedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `marlacedb` DEFAULT CHARACTER SET utf8 ;
USE `marlacedb` ;

-- -----------------------------------------------------
-- Table `marlacedb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marlacedb`.`users` ;

CREATE TABLE IF NOT EXISTS `marlacedb`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(64) NOT NULL,
  `last_name` VARCHAR(64) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` TEXT NOT NULL,
  `description` VARCHAR(1024) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marlacedb`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marlacedb`.`categories` ;

CREATE TABLE IF NOT EXISTS `marlacedb`.`categories` (
  `category_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`, `user_id`),
  INDEX `fk_categories_user_idx` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `category_id_UNIQUE` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_categories_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `marlacedb`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marlacedb`.`transactions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marlacedb`.`transactions` ;

CREATE TABLE IF NOT EXISTS `marlacedb`.`transactions` (
  `transaction_id` INT NOT NULL AUTO_INCREMENT,
  `category_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `note` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`transaction_id`, `category_id`, `user_id`),
  UNIQUE INDEX `transaction_id_UNIQUE` (`transaction_id` ASC) VISIBLE,
  INDEX `fk_transactions_categories1_idx` (`category_id` ASC, `user_id` ASC) VISIBLE,
  CONSTRAINT `fk_transactions_categories1`
    FOREIGN KEY (`category_id` , `user_id`)
    REFERENCES `marlacedb`.`categories` (`category_id` , `user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- SELECT c.`category_id`, c.`user_id`, c.`title`, c.`description`, coalesce(sum(t.`amount`), 0) as `total_expense`  
-- 	FROM `categories` c INNER JOIN `transactions` t 
--     ON c.`category_id` = t.`category_id` 
--     WHERE c.`user_id` = ? AND c.`category_id` = ? 
--     GROUP BY c.`category_id`;
